services:
  live-monitor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: live-monitor
    restart: unless-stopped
    environment:
      API_URL: "http://100.119.197.81:8002/dashboard/extruder-latest-values"
      API_TIMEOUT_SECONDS: "5"
      POLL_INTERVAL_SECONDS: "10"
      WINDOW_DURATION_SECONDS: "300"
      CONFIRMATION_WINDOWS: "3"
      BACKEND_BASE_URL: "http://host.docker.internal:8002"
      MACHINE_ID: "6f37c433-44e9-4a66-b019-cc342a95cc54"
    volumes:
      - ./live_monitor/ml_data:/app/live_monitor/ml_data
    ports:
      - "8001:8001"
